# Generated by Django 3.0.6 on 2020-05-22 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testlogin', '0001_initial'),
    ]

    operations = [
    ]
